apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "target-cua"
  namespace: "sandbox-cua"
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        -
          name: "app"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: "RuntimeDefault"
